[project]
name = "partdiff-common"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pydantic>=2.12.5",
    "pympler>=1.1",
]
[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"
