[project]
name = "0-simple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "partdiff-common",
]

[tool.uv.sources]
partdiff-common = { path = "../partdiff_common" }
