name: Correctness Check (nuitka)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.8"

      - name: Set up Python
        run: uv python install

      - name: Build with Nuitka # Workaround
        run: |
          uv export --no-hashes -o requirements.txt && \
          python -m venv .venv && \
          source .venv/bin/activate && \
          pip install -r requirements.txt && \
          nuitka --output-filename=partdiff main.py
        
      - name: Clone partdiff_tester
        run: git clone https://github.com/parcio/partdiff_tester.git

      - name: Run correctness check
        run: |
          cd partdiff_tester && \
          uv run pytest -n auto --verbose \
            --executable='./partdiff' \
            --cwd='../nuitka' \
            --strictness=4 \
            --shuffle=42 \
            --filter='o:{"lines": "0"}'
