name: Correctness Check (simple)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.8"

      - name: Set up Python
        run: uv python install

      - name: Clone partdiff_tester
        run: git clone https://github.com/parcio/partdiff_tester.git

      - name: Run correctness check
        run: |
          cd partdiff_tester && \
          uv run pytest -n auto --verbose \
            --executable='uv run main.py' \
            --cwd='../simple' \
            --strictness=4 \
            --shuffle=42 \
            --filter='o:{"lines": "0"}'
